[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
solc = "0.8.26"
optimizer = true
optimizer_runs = 1_000_000
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
